title: Letters from France
description: Canadians invastion of southern France
theme: just-the-docs

url: https://france.iancrosby.ca

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
